# Generated by Django 6.0.7 on 2026-07-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CRM_Record',
        ),
    ]
